version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: trs
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - trs-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - trs-redis:/var/lib/redis/data

  trs:
    image: $DOCKER_USERNAME/the-recipe-spreadsheet:latest
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    image: $DOCKER_USERNAME/the-recipe-spreadsheet:latest
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    image: $DOCKER_USERNAME/the-recipe-spreadsheet-nginx:latest
    links:
      - trs
    ports:
      - '8020:8020'

volumes:
  trs-postgres:
  trs-redis:

